# Generated by Django 4.1.1 on 2022-09-21 05:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userpreferences', '0002_showtouser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShowToUser',
            new_name='SharePreference',
        ),
    ]
