# Generated by Django 4.1.1 on 2022-09-21 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userpreferences', '0004_sharepreference_seeingfrom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharepreference',
            name='SeeingFrom',
        ),
        migrations.CreateModel(
            name='GetPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SeeingFrom', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
