# Generated by Django 4.0.5 on 2022-08-25 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userincome', '0002_alter_userincome_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userincome',
            name='source',
            field=models.CharField(max_length=256),
        ),
    ]
